version: 2
updates:
  - package-ecosystem: gradle
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    milestone: 216 # main
    labels:
      - 'in: build'
      - 'type: dependency-upgrade'
    ignore:
      - dependency-name: org.junit:junit-bom
        update-types:
          - version-update:semver-major
      - dependency-name: org.mockito:mockito-bom
        update-types:
          - version-update:semver-major
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'type: task'
      - 'in: build'
  - package-ecosystem: gradle
    target-branch: 4.0.x
    directory: /
    schedule:
      interval: weekly
    milestone: 202 # 4.0.x
    labels:
      - 'in: build'
      - 'type: dependency-upgrade'
    ignore:
      - dependency-name: org.junit:junit-bom
        update-types:
          - version-update:semver-major
      - dependency-name: org.mockito:mockito-bom
        update-types:
          - version-update:semver-major
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: github-actions
    target-branch: 4.0.x
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'type: task'
      - 'in: build'
  - package-ecosystem: gradle
    target-branch: 4.1.x
    directory: /
    schedule:
      interval: weekly
    milestone: 203 # 4.1.x
    labels:
      - 'in: build'
      - 'type: dependency-upgrade'
    ignore:
      - dependency-name: org.junit:junit-bom
        update-types:
          - version-update:semver-major
      - dependency-name: org.mockito:mockito-bom
        update-types:
          - version-update:semver-major
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: github-actions
    target-branch: 4.1.x
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'type: task'
      - 'in: build'
  - package-ecosystem: npm
    target-branch: docs-build
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'type: dependency-upgrade'
      - 'in: build'
  - package-ecosystem: github-actions
    target-branch: docs-build
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'type: task'
      - 'in: build'
