BEGIN
	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE SPRING_SESSION_ATTRIBUTES';
	EXCEPTION
		WHEN OTHERS THEN
			IF SQLCODE != -942 THEN
				RAISE;
			END IF;
	END;
	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE SPRING_SESSION';
	EXCEPTION
		WHEN OTHERS THEN
			IF SQLCODE != -942 THEN
				RAISE;
			END IF;
	END;
END;
