version: 2
updates:
{{#main}}
  - package-ecosystem: gradle
    {{>target-branch}}
    {{>directory}}
    {{>schedule}}
    {{>labels}}
    ignore:
      - dependency-name: org.junit:junit-bom
        update-types:
          - version-update:semver-major
      - dependency-name: org.mockito:mockito-bom
        update-types:
          - version-update:semver-major
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    {{>target-branch}}
    {{>directory}}
    {{>schedule}}
    labels:
      - 'type: task'
      - 'in: build'
{{/main}}
{{#feature-branches}}
  - package-ecosystem: gradle
    {{>target-branch}}
    {{>directory}}
    {{>schedule}}
    {{>labels}}
    ignore:
      - dependency-name: org.junit:junit-bom
        update-types:
          - version-update:semver-major
      - dependency-name: org.mockito:mockito-bom
        update-types:
          - version-update:semver-major
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: github-actions
    {{>target-branch}}
    {{>directory}}
    {{>schedule}}
    labels:
      - 'type: task'
      - 'in: build'
{{/feature-branches}}
{{#docs-build}}
  - package-ecosystem: npm
    {{>target-branch}}
    {{>directory}}
    {{>schedule}}
    labels:
      - 'type: dependency-upgrade'
      - 'in: build'
  - package-ecosystem: github-actions
    {{>target-branch}}
    {{>directory}}
    {{>schedule}}
    labels:
      - 'type: task'
      - 'in: build'
{{/docs-build}}
