name: CI - Test

on:
  workflow_call:
    inputs:
      java-version:
        description: Java version to test with
        type: string
        default: '17'
      runner:
        description: Runner to test on
        type: string
        default: ubuntu-latest
      release-channel:
        description: The release channel for this test; oss or internal
        type: string
        default: oss

jobs:
  test:
    name: Test Against Snapshots
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: secrets
        name: Resolve Secret Names
        uses: ./.github/actions/compute-secrets
        with:
          release-channel: ${{ inputs.release-channel }}
      - name: Adapt SNAPSHOT Suffix for Internal CI
        if: inputs.release-channel == 'internal'
        run: sed -i -E '/^version=/ s/-SNAPSHOT$/-INTERNAL-SNAPSHOT/' gradle.properties
      - name: Test Project
        uses: spring-io/spring-security-actions/test@96df48300f5fa058d0765832d48a534cc6a378d5 # 0.0.3
        env:
          ORG_GRADLE_PROJECT_artifactoryUsername: ${{ secrets[steps.secrets.outputs.dependencies-username] }}
          ORG_GRADLE_PROJECT_artifactoryPassword: ${{ secrets[steps.secrets.outputs.dependencies-password] }}
        with:
          java-version: ${{ inputs.java-version }}
          gradle-args: -Psnapshot -PtestToolchain=${{ inputs.java-version }}
