name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
  schedule:
    - cron: '0 10 * * *' # Once per day at 10am UTC
  workflow_dispatch: # Manual trigger

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: spring-io/spring-security-release-tools/.github/workflows/build.yml@d6c65d3013c0888e2c9cbae9f4beda610994776c # v1.0.16
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 17 ]
    with:
      runs-on: ${{ matrix.os }}
      java-version: ${{ matrix.jdk }}
      distribution: temurin
    secrets: inherit
  compute-version:
    name: Compute Version
    runs-on: ubuntu-latest
    outputs:
      snapshot: ${{ steps.project-version.outputs.snapshot }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      - id: project-version
        name: Extract Project Version
        uses: spring-io/spring-release-actions/compute-version@1b8671612c3eb3d9b9763e2d7b66f1a80d00ee95 # 0.0.6
  deploy-artifacts:
    name: Deploy Artifacts
    needs: [ build, compute-version ]
    if: needs.compute-version.outputs.snapshot == 'true'
    uses: spring-io/spring-security-release-tools/.github/workflows/deploy-artifacts.yml@3f6cc7ffc137ca160061749d5f34dc30d5f36986 # v1.0.17
    with:
      should-deploy-artifacts: ${{ needs.build.outputs.should-deploy-artifacts }}
      default-publish-milestones-central: true
    secrets: inherit
