name: Dependabot - Auto-merge PR

on:
  pull_request:
    branches:
      - main
      - '*.x'
      - 'docs-build'

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all
    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@bf2c65c148fb74b6bd54417222662ef587463765 # main
    with:
      mergeArguments: --auto --rebase
