name: Pull Request - Build

on: pull_request

permissions:
  contents: read

env:
  JAVA_VERSION: '17'

jobs:
  build:
    name: Build
    runs-on: ${{ vars.UBUNTU_RUNS_ON }}
    if: github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: secrets
        uses: ./.github/actions/compute-secrets
      - uses: spring-io/spring-security-actions/pr-build@96df48300f5fa058d0765832d48a534cc6a378d5 # 0.0.3
        env:
          ORG_GRADLE_PROJECT_artifactoryUsername: ${{ secrets[steps.secrets.outputs.dependencies-username] }}
          ORG_GRADLE_PROJECT_artifactoryPassword: ${{ secrets[steps.secrets.outputs.dependencies-password] }}
        with:
          java-version: ${{ env.JAVA_VERSION }}
  build-check:
    name: Build
    needs: build
    if: failure() || cancelled()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
