name: Rebuild Search Index
on:
  schedule:
    - cron: '0 10 * * *' # Once per day at 10am UTC
  workflow_dispatch:
permissions: read-all
jobs:
  build:
    if: github.repository_owner == 'spring-projects'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: docs-build
          fetch-depth: 1
      - name: Dispatch
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
        run: gh workflow run rebuild-search-index.yml -r $(git rev-parse --abbrev-ref HEAD)
