name: Release Announcements - Stage

on:
  push:
    tags: '**'
  workflow_dispatch:
    inputs:
      version:
        description: The version to stage
        required: true
        type: string

permissions:
  actions: write
  contents: write
  issues: read

jobs:
  stage-release-announcements:
    name: Stage Release Announcements
    uses: spring-io/spring-security-release-tools/.github/workflows/release-announcements-stage.yml@6803d775925cdca5990e1e68b5a1c1fe38fa3947 # v1.0.20
    with:
      version: ${{ inputs.version || github.ref_name }}
    secrets: inherit
