name: Release Announcements - Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to publish
        required: true

permissions:
  actions: write
  contents: read
  issues: write

jobs:
  publish-release-announcements:
    name: Publish Release Announcements
    uses: spring-io/spring-security-release-tools/.github/workflows/release-announcements-publish.yml@6803d775925cdca5990e1e68b5a1c1fe38fa3947 # v1.0.20
    with:
      version: ${{ inputs.version }}
    secrets: inherit
