name: Release Announcements - Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to publish
        required: true
        type: string

permissions:
  actions: write
  contents: read
  issues: write

jobs:
  publish-release-announcements:
    name: Publish Release Announcements
    if: ${{ !github.event.repository.fork }}
    uses: spring-io/spring-security-release-tools/.github/workflows/release-announcements-publish.yml@d6c65d3013c0888e2c9cbae9f4beda610994776c # v1.0.16
    with:
      version: ${{ inputs.version }}
    secrets: inherit
