name: Release Announcements - Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to publish
        required: true

permissions:
  actions: write
  contents: read
  issues: write

jobs:
  publish-release-announcements:
    name: Publish Release Announcements
    uses: spring-io/spring-security-release-tools/.github/workflows/release-announcements-publish.yml@d1199a03aee6023578d50c34ec6f09e37889672c # v1.0.19
    with:
      version: ${{ inputs.version }}
    secrets: inherit
