name: Trigger Dependabot Auto Merge Forward

on:
  push:
    branches:
      - '*.x'

permissions: read-all

jobs:
  trigger-worflow:
    name: Trigger Workflow
    runs-on: ubuntu-latest
    if: ${{ github.event.commits[0].author.username == 'dependabot[bot]' && github.repository == 'spring-projects/spring-session' }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: trigger
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
        run: gh workflow run dependabot-auto-merge-forward.yml -r main
